select 
        a.dtref,
        a.idcliente,
        a.IdadeDias ,
        a.QtDias_Ativacao_Vida ,
        a.QtDias_Ativacao_7Dias ,
        a.QtDias_Ativacao_14Dias ,
        a.QtDias_Ativacao_28Dias ,
        a.QtDias_Ativacao_56Dias ,
        a.Qt_Transacao_Vida ,
        a.Qt_Transacao_7Dias ,
        a.Qt_Transacao_14Dias ,
        a.Qt_Transacao_28Dias ,
        a.Qt_Transacao_56Dias ,
        a.SaldoVida ,
        a.Saldo_7Dias ,
        a.Saldo_14Dias ,
        a.Saldo_28Dias ,
        a.Saldo_56Dias ,
        a.QtdePontos_Positivo_Vida ,
        a.QtdePontos_Positivo_7Dias ,
        a.QtdePontos_Positivo_14Dias ,
        a.QtdePontos_Positivo_28Dias ,
        a.QtdePontos_Positivo_56Dias ,
        a.QtdePontos_Negativo_Vida ,
        a.QtdePontos_Negativo_7Dias ,
        a.QtdePontos_Negativo_14Dias ,
        a.QtdePontos_Negativo_28Dias ,
        a.QtdePontos_Negativo_56Dias ,
        a.qt_trn_Manha ,
        a.qt_trn_Tarde ,
        a.qt_trn_Noite ,
        a.pct_trn_Manha ,
        a.pct_trn_Tarde ,
        a.pct_trn_Noite ,
        a.qtd_Trn_Dia_Vida ,
        a.qtd_Trn_Dia_7dias ,
        a.qtd_Trn_Dia_14dias ,
        a.qtd_Trn_Dia_28dias ,
        a.qtd_Trn_Dia_56dias ,
        a.Pct_Ativacao_Mau ,
        a.qt_horas_vida ,
        a.qt_horas_vida_7dias ,
        a.qt_horas_vida_14dias ,
        a.qt_horas_vida_28dias ,
        a.qt_horas_vida_56dias ,
        a.MediaIntervaloDias_Vida ,
        a.MediaIntervaloDias_28dias ,
        a.qtdeChatMessage ,
        a.qtdeAirflow ,
        a.qtdeLover ,
        a.qtdeResgatarPonei ,
        a.qtdeLista ,
        a.qtdeStreak ,
        a.qtdeStreamElements ,
        a.qtdeReembolsoStreamElements ,
        a.qtdeRPG ,
        a.qtdechurn,
        b.qt_Freq_28_dias ,
        b.Ciclo_Vida_Atual ,
        b.Ciclo_Vida_D28 ,
        b.pct_Curioso ,
        b.pct_Desencantada ,
        b.pct_Fiel ,
        b.pct_Zumbi ,
        b.pct_Turista ,
        b.pct_Reconquista ,
        b.pct_Reborn ,
        b.Qtde_Frequencia_Grupo ,
        b.ratio_freq_Grupo ,
        c.Qtd_Cursos_Completos ,
        c.Qtd_Cursos_Incompletos ,
        c.carreira ,
        c.coleta_dados ,
        c.ds_databricks ,
        c.ds_pontos ,
        c.estat_2024 ,
        c.estat_2025 ,
        c.f1_lake ,
        c.github_2024 ,
        c.github_2025 ,
        c.go_2026 ,
        c.ia_canal_2026 ,
        c.lago_mago_2024 ,
        c.loyalty_pred_2025 ,
        c.ML_2025 ,
        c.matchmaking_2024 ,
        c.ml_2024 ,
        c.mlflow_2025 ,
        c.nekt_2025 ,
        c.pandas_2024 ,
        c.pandas_2025 ,
        c.plataforma_ml_2026 ,
        c.python_2024 ,
        c.python_2025 ,
        c.ragia ,
        c.speed_f1 ,
        c.sql_2020 ,
        c.sql_2025 ,
        c.streamlit_2025 ,
        c.trampar_lakehouse_2024 ,
        c.tse_analytics_2024 ,
        c.Qt_Dias_ult_atividade 

from 
    fs_transacional a
        
    left join fs_ciclo_de_vida b
        on a.idCliente = b.idCliente and 
           a.dtref = b.dtref 

    left join fs_education c
        on a.idCliente = c.idCliente and 
           a.dtref = c.dtref 

where a.dtref = (select max(dtref) from fs_transacional) 
